# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rustgd, .registration = TRUE
NULL

rustgd_activate <- function(session_dir) .Call(wrap__rustgd_activate, session_dir)

rustgd_set_size <- function(width, height) .Call(wrap__rustgd_set_size, width, height)

rustgd_check_new_page <- function() .Call(wrap__rustgd_check_new_page)

rustgd_check_drew <- function() .Call(wrap__rustgd_check_drew)

rustgd_set_replay_mode <- function(on) .Call(wrap__rustgd_set_replay_mode, on)

rustgd_set_current_page <- function(page) .Call(wrap__rustgd_set_current_page, page)

# nolint end
